### ISSUE TITLE
Does ArduinoMDNS update its mDNS cache automaticly?

### ISSUE THREAD

**Issue by JulianS-Uni** [arduino-libraries/ArduinoMDNS#5]
I am not that into mDNS but I read several times now that mDNS machines can update their mDNS cache automaticly.

When an mDNS client needs to resolve a host name, it sends an IP multicast query message that asks the host having that name to identify itself. That target machine then multicasts a message that includes its IP address. All machines in that subnet can then use that information to update their mDNS caches. [Wikipedia](https://en.wikipedia.org/wiki/Multicast_DNS#Protocol_overview)

Does ArduinoMDNS library does this too or is it only possible to query for a host or a service which are both blocking operations?

**Comment by sandeepmistry** [comment]
Hi @JulianS-Uni,

> Does ArduinoMDNS library does this too or is it only possible to query for a host or a service which are both blocking operations?

The library currently only supports the second, it is "only possible to query for a host or a service which are both blocking operations".
