### ISSUE TITLE
Please release version and tag 

### ISSUE THREAD

**Issue by rzr** [arduino-libraries/ArduinoMDNS#6]
I am looking a way to to pin my dependencies, would this be possible to have tags in this repo ?

Eventually aligned the arduino sdk ones

**Comment by thekunalsaini** [comment]
@rzr @per1234  Can you elaborate what you are trying to say?

**Comment by rzr** [comment]
having tags in git repo would help because my project uses makefiles to pull libs using git clone.

**Comment by MisterAwesome23** [comment]
I tried creating a v1.0.0 release and tag on my fork. You can have a look at it [here](https://github.com/MisterAwesome23/ArduinoMDNS/releases) 

I read through a few standard rules and naming conventions before giving it a base numbers. Few resources if someone wants to follow up-
1. https://semver.org/
2. https://softwareengineering.stackexchange.com/questions/345006/why-popular-repositories-use-release-version-as-a-release-title-in-github
3. https://rollout.io/blog/best-practices-when-versioning-a-release/

Now though I've added the release and tag to my fork, it turn out that it can't be included in a pull request and hence I can not create a PR for this. More on this [here](https://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request).

>" A pull request does not include tags. A pull request is only a pointer to a thread of commits (a branch) in your repository that you're proposing another repository to merge."

>"The best and only method really becomes to ask the maintainer to issue a release for his code by tagging if that's the way they do it but that is to their discretion!"

So, @TrippyLighting or any maintainer for this, kindly look into my release on [fork](https://github.com/MisterAwesome23/ArduinoMDNS/releases), preferably add appropriate release description and make changes.

**Comment by alranel** [comment]
Released! Will be available in the library manager shortly.
